### ISSUE TITLE
Error of unrecognized variable when calling massDS.GausFlag(j) in MIBIfilterAggregatesAllChannels.m

### ISSUE THREAD

**Issue by YubinXie** [lkeren/MIBIAnalysis#10]
Thanks for providing the excellent works! I successfully ran the scripts before MIBIfilterAggregatesAllChannels.m on sample data. However, error comes when it comes to line 40 massDS.GausFlag(j) in MIBIfilterAggregatesAllChannels.m.

I checked massDS, which is a 49*9 dataset with Isotope, Label, Start, Stop, BaselineEnd, Batch, NoiseT, nnk information. I did not see GausFlag. Did I miss anything? Thank you.

Note: I only have one point in the sample data, so that I changed the corePath from two points to only one point.

`corePath = {'SampleData/extracted/cleanData/Point1/'}`

**Comment by Hazmatius** [comment]
Hi! If you look in the "MIBI low level analysis tutorial" doc under section 4.6 in the last paragraph, it says to add GausFlag manually, and then fill in 1 or 0 for each channel if you do or do not want to use gaussian filtering, respectively.
