### ISSUE TITLE
Where can I find the data?

### ISSUE THREAD

**Issue by livnatje** [lkeren/MIBIAnalysis#19]
Thanks for making the code and data available! Beautiful work!

Is it possible to get the processed data, instead of just the images, meaning the level of each marker across the cells + the cells' coordinates?

Couldn't find this on the website/supplementary, so I must be missing something.

**Comment by chsher** [comment]
Same here, could you share the processed data?

**Comment by ngreenwald** [comment]
Yes, the link is here: https://www.angelolab.com/mibi-data

**Comment by chsher** [comment]
Thanks @ngreenwald! How do you load the objects from the p#_labeledcellData.tiff files? Using Matlab’s TIFF-reading function does not seem to yield the 1-to-N integer labels for the objects --
```
t = Tiff(‘xxx.tiff','r');
imageData = read(t); 
```
Do you have the x-y coordinates for the segmented objects?

**Comment by ngreenwald** [comment]
I'm not sure about Matlab, but both Python and ImageJ allow you to read the TIFF in and get the 1-N integer labels.

**Comment by Shawnmhy** [comment]
@ngreenwald Hello, could you please share the clinical data? Like the survival for each patient, thank you.

**Comment by ngreenwald** [comment]
Hey @Shawnmhy, the clinical data is in Supplementary Table 2 in the original publication

**Comment by Shawnmhy** [comment]
@ngreenwald , I am wondering whether the marker expression value found in the cellData.csv has been transformed or not?

**Comment by ngreenwald** [comment]
I believe they are size normalized and arcsinh transformed

**Comment by ngreenwald** [comment]
But you can check the methods to confirm

**Comment by Shawnmhy** [comment]
Thanks, I checked and it is size normalized and arcsinh transformed. Another question is what is the unit of coordinates and area in the single cell dataset ? is it pixel or microns?
