### ISSUE TITLE
As for the Tumor-Immune mixing analysis mentioned in the article, may I ask which code it is ?

### ISSUE THREAD

**Issue by Masteryuanli** [lkeren/MIBIAnalysis#20]
your work is very good. we measured some Imageing mass cytometry datasets,   and realy wanted to using your paper method,
 and find source code to analysis our data.   I look forward to your reply. thanks!

**Comment by ngreenwald** [comment]
All of the methods from the paper can be found here: https://github.com/angelolab/TNBC

**Comment by Masteryuanli** [comment]
thank you very much!
